nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su codigo-seccion: ")
sede = input("Ingrese su sede: ")

print("\nInformacion ingresada:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Codigo_seccion:", codigo_seccion)
print("Sede:", sede)